# Importing Libraries and Loading Dataset

In [24]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

In [10]:
df = pd.read_json("../Dataset/Raw_Data/rossmann_store_sales.json")

# Dataset Information

In [3]:
df.head()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,5,2015-07-31,5263,555,1,1,0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,5,2015-07-31,6064,625,1,1,0,1,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,5,2015-07-31,8314,821,1,1,0,1,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,5,2015-07-31,13995,1498,1,1,0,1,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,5,2015-07-31,4822,559,1,1,0,1,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN

# Data Preprocessing

Purpose:

Prepare the Rossmann Store Sales Dataset
for machine learning model development.

Tasks:

1. Missing Value Treatment
2. Data Cleaning
3. Date Feature Extraction
4. Categorical Encoding
5. Feature Engineering
6. Train/Test Dataset Preparation

# Missing Value Treatment

In [4]:
missing_values = (
    df.isnull().sum().sort_values(ascending=False)
)

missing_values[
    missing_values>0
]

Promo2SinceWeek              508031
PromoInterval                508031
Promo2SinceYear              508031
CompetitionOpenSinceYear     323348
CompetitionOpenSinceMonth    323348
CompetitionDistance            2642
dtype: int64

### Observation

Competition and promotion-related variables
contain substantial amounts of missing data.

Appropriate imputation strategies must be applied
before machine learning models are developed.

# Missing Value Strategy

In [31]:
df["CompetitionDistance"] = (
    df["CompetitionDistance"].fillna(
        df["CompetitionDistance"].median()
    )
)

df["CompetitionOpenSinceMonth"] = (
    df["CompetitionOpenSinceMonth"].fillna(
        df["CompetitionOpenSinceMonth"].median()
    )
)

df["CompetitionOpenSinceYear"]= (
    df["CompetitionOpenSinceYear"].fillna(
        df["CompetitionOpenSinceYear"].median()
    )
)

df["Promo2SinceWeek"] = (
    df["Promo2SinceWeek"].fillna(
        df["Promo2SinceWeek"].median()
    )
)

df["Promo2SinceYear"] = (
    df["Promo2SinceYear"].fillna(
        df["Promo2SinceYear"].median()
    )
)

df["PromoInterval"] = (
    df["PromoInterval"].fillna("None")
)

# Verifying Missing Values

In [32]:
df.isnull().sum()

Store                        0
DayOfWeek                    0
Date                         0
Sales                        0
Customers                    0
Open                         0
Promo                        0
StateHoliday                 0
SchoolHoliday                0
StoreType                    0
Assortment                   0
CompetitionDistance          0
CompetitionOpenSinceMonth    0
CompetitionOpenSinceYear     0
Promo2                       0
Promo2SinceWeek              0
Promo2SinceYear              0
PromoInterval                0
Year                         0
Month                        0
Day                          0
Quarter                      0
dtype: int64

### Observation

Missing values were identified in competition-related and promotion-related variables.

Median input was applied to CompetitionDistance, while zero-value and placeholder-value imputation strategies were applied to remaining cariables.

According to the treatment, no missing values were remaining among our dataset. Which made our dataset a valuable and suitable one for our future engineering and machine-learning model development.

# Date Feature Engineering

In [19]:
df["Date"] = pd.to_datetime(df["Date"])

df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Day"] = df["Date"].dt.day
df["Quarter"] = df["Date"].dt.quarter

In [20]:
df[[
    "Date",
    "Year",
    "Month",
    "Day",
    "Quarter"
]].head()

        Date  Year  Month  Day  Quarter
0 2015-07-31  2015      7   31        3
1 2015-07-31  2015      7   31        3
2 2015-07-31  2015      7   31        3
3 2015-07-31  2015      7   31        3
4 2015-07-31  2015      7   31        3

# Data Type Inspection

In [22]:
df.info()

<class 'pandas.DataFrame'>
Index: 1017209 entries, 0 to 1017208
Data columns (total 22 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   Store                      1017209 non-null  int64
 1   DayOfWeek                  1017209 non-null  int64
 2   Date                       1017209 non-null  datetime64[us]
 3   Sales                      1017209 non-null  int64
 4   Customers                  1017209 non-null  int64
 5   Open                       1017209 non-null  int64
 6   Promo                      1017209 non-null  int64
 7   StateHoliday               1017209 non-null  object
 8   SchoolHoliday              1017209 non-null  int64
 9   StoreType                  1017209 non-null  str
 10  Assortment                 1017209 non-null  str
 11  CompetitionDistance        1014567 non-null  float64
 12  CompetitionOpenSinceMonth  693861 non-null   float64
 13  CompetitionOpenSinceYear   693861 non-null   float64
 14  Promo2                     1017209 non-null  int64
 15  Promo2SinceWeek            509178 non-null   float64
 16  Promo2SinceYear            509178 non-null   float64
 17  PromoInterval              509178 non-null   str
 18  Year                       1017209 non-null  int32
 19  Month                      1017209 non-null  int32
 20  Day                        1017209 non-null  int32
 21  Quarter                    1017209 non-null  int32
dtypes: datetime64[us](1), float64(5), int32(4), int64(8), object(1), str(3)
memory usage: 172.4+ MB

# Categorical Encoding

In [23]:
for col in [
    "StateHoliday",
    "StoreType",
    "Assortment",
    "PromoInterval"
]:
    print("\n", col)
    print(df[col].unique())

 StateHoliday
['0' 'a' 'b' 'c' 0]

 StoreType
<ArrowStringArray>
['c', 'a', 'd', 'b']
Length: 4, dtype: str

 Assortment
<ArrowStringArray>
['a', 'c', 'b']
Length: 3, dtype: str

 PromoInterval
<ArrowStringArray>
[nan, 'Jan,Apr,Jul,Oct', 'Feb,May,Aug,Nov', 'Mar,Jun,Sept,Dec']
Length: 4, dtype: str

In [29]:
le = LabelEncoder()
categorical_cols = [
    "StateHoliday",
    "StoreType",
    "Assortment",
    "PromoInterval"
]

for col in categorical_cols:
    df[col] = le.fit_transform(
        df[col].astype(str)
    )

In [30]:
df.info()

<class 'pandas.DataFrame'>
Index: 1017209 entries, 0 to 1017208
Data columns (total 22 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   Store                      1017209 non-null  int64
 1   DayOfWeek                  1017209 non-null  int64
 2   Date                       1017209 non-null  datetime64[us]
 3   Sales                      1017209 non-null  int64
 4   Customers                  1017209 non-null  int64
 5   Open                       1017209 non-null  int64
 6   Promo                      1017209 non-null  int64
 7   StateHoliday               1017209 non-null  int64
 8   SchoolHoliday              1017209 non-null  int64
 9   StoreType                  1017209 non-null  int64
 10  Assortment                 1017209 non-null  int64
 11  CompetitionDistance        1014567 non-null  float64
 12  CompetitionOpenSinceMonth  693861 non-null   float64
 13  CompetitionOpenSinceYear   693861 non-null   float64
 14  Promo2                     1017209 non-null  int64
 15  Promo2SinceWeek            509178 non-null   float64
 16  Promo2SinceYear            509178 non-null   float64
 17  PromoInterval              1017209 non-null  int64
 18  Year                       1017209 non-null  int32
 19  Month                      1017209 non-null  int32
 20  Day                        1017209 non-null  int32
 21  Quarter                    1017209 non-null  int32
dtypes: datetime64[us](1), float64(5), int32(4), int64(12)
memory usage: 163.0 MB

# Dropping Date

In [33]:
df_ml = df.drop(
    columns = ["Date"]
)

In [34]:
df_ml.info()

<class 'pandas.DataFrame'>
Index: 1017209 entries, 0 to 1017208
Data columns (total 21 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   Store                      1017209 non-null  int64
 1   DayOfWeek                  1017209 non-null  int64
 2   Sales                      1017209 non-null  int64
 3   Customers                  1017209 non-null  int64
 4   Open                       1017209 non-null  int64
 5   Promo                      1017209 non-null  int64
 6   StateHoliday               1017209 non-null  int64
 7   SchoolHoliday              1017209 non-null  int64
 8   StoreType                  1017209 non-null  int64
 9   Assortment                 1017209 non-null  int64
 10  CompetitionDistance        1017209 non-null  float64
 11  CompetitionOpenSinceMonth  1017209 non-null  float64
 12  CompetitionOpenSinceYear   1017209 non-null  float64
 13  Promo2                     1017209 non-null  int64
 14  Promo2SinceWeek            1017209 non-null  float64
 15  Promo2SinceYear            1017209 non-null  float64
 16  PromoInterval              1017209 non-null  int64
 17  Year                       1017209 non-null  int32
 18  Month                      1017209 non-null  int32
 19  Day                        1017209 non-null  int32
 20  Quarter                    1017209 non-null  int32
dtypes: float64(5), int32(4), int64(12)
memory usage: 155.2 MB

## Categorical Feature Encoding

Categorical variables including
StateHoliday, StoreType,
Assortment, and PromoInterval
were transformed into numeric
representations using Label Encoding.

This transformation enabled the
dataset to be consumed by machine
learning algorithms, which require
numerical input features.

The resulting dataset contains no
missing values and is fully prepared
for supervised learning tasks.